name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore RapidConsole.sln
  
    - name: Build solution
      run: dotnet build RapidConsole.sln --no-restore --configuration Release
  
    - name: Run tests
      run: dotnet test RapidConsole.sln --no-build --verbosity normal --configuration Release